### ISSUE TITLE
Missing external_* checks in some roles

### ISSUE THREAD

**Issue by gavillom** [oxedions/bluebanquise#37]
Hey ,

I'm trying to use bluebanquise to deploy a cluster stack. I'm not interested in using external servers at all. So I just removed values from example in my inventory. The file (/etc/ansible/inventory/gorup_vars/general_settings/external.yml) is like this : 

```
external_time:
  time_server:
    server: # List of possible time servers
    pool: # List of possible time pools
  time_client:
    server: 
    pool: 

external_dns:
  dns_server: # set as forwarders in named.conf
  dns_client: # set directly on client side in resolv.conf

# Hosts defined here will be automatically added into /etc/hosts and into DNS configuration
external_hosts:
```

Then I got the following error on several roles (at least hostsfile, dns_client, dns_server) : 

```
AnsibleError: Unexpected templating type error occurred on (#### Blue Banquise file ####
): 'NoneType' object is not iterable
```
It feels like templates need to check if lists length is more than 0.

Mathis
